import { Activity, MaterialItem } from '@/types';

export const INITIAL_ACTIVITIES: Activity[] = [
  { id: 1, phase: 'Critical Civil & External', name: 'Waterproofing', start: '2026-08-01', end: '2026-09-20', priority: 'High', resp: 'Site Engineer', dep: '', status: 'In Progress', pct: 50, remarks: 'Urgent — civil site team on site' },
  { id: 2, phase: 'Critical Civil & External', name: 'Plaster', start: '2026-09-09', end: '2026-09-12', priority: 'High', resp: 'RS Construction', dep: 'Brick Masonary', status: 'In Progress', pct: 50, remarks: '' },
  { id: 3, phase: 'Critical Civil & External', name: 'Stone Masonary', start: '2026-09-09', end: '2026-09-16', priority: 'High', resp: 'RS Construction', dep: 'Brick Masonary', status: 'In Progress', pct: 50, remarks: '' },
  { id: 4, phase: 'Critical Civil & External', name: 'Brick Masonary', start: '2026-09-09', end: '2026-09-13', priority: 'High', resp: 'RS Construction', dep: '', status: 'In Progress', pct: 50, remarks: '' },
  { id: 5, phase: 'Critical Civil & External', name: 'MS Fabrication Roof', start: '2026-09-14', end: '2026-09-20', priority: 'High', resp: 'Fabricator', dep: '', status: 'Not Started', pct: 0, remarks: 'Selection done — delivery pending' },
  { id: 6, phase: 'Critical Civil & External', name: 'Roof Flooring', start: '2026-09-21', end: '2026-09-27', priority: 'High', resp: 'Nanak', dep: 'MS Fabrication Roof', status: 'Not Started', pct: 0, remarks: 'Crazy pattern — selection pending' },
  { id: 7, phase: 'Critical Civil & External', name: 'Outer Area Development', start: '2026-09-14', end: '2026-09-26', priority: 'High', resp: 'RS Construction', dep: '', status: 'In Progress', pct: 50, remarks: '' },
  { id: 8, phase: 'Swimming Pool', name: 'Swimming Pool Work', start: '2026-09-14', end: '2026-09-26', priority: 'High', resp: 'DD Pools', dep: '', status: 'In Progress', pct: 50, remarks: '' },
  { id: 9, phase: 'Services', name: 'Plumbing Drainage', start: '2026-09-14', end: '2026-09-18', priority: 'High', resp: 'Plumbing Team', dep: '', status: 'Completed', pct: 100, remarks: '' },
  { id: 10, phase: 'Services', name: 'BT Plumbing', start: '2026-09-19', end: '2026-09-23', priority: 'High', resp: 'Plumbing Team', dep: '', status: 'Not Started', pct: 0, remarks: 'Fittings partially delivered' },
  { id: 11, phase: 'Services', name: 'Electrical', start: '2026-09-21', end: '2026-10-01', priority: 'High', resp: 'Ganesh Ji', dep: '', status: 'Not Started', pct: 0, remarks: 'All selections pending' },
  { id: 12, phase: 'Finishes', name: 'False Ceiling', start: '2026-10-02', end: '2026-10-08', priority: 'High', resp: 'False Ceiling Vendor', dep: 'Electrical', status: 'In Progress', pct: 50, remarks: '' },
  { id: 13, phase: 'Finishes', name: 'Wall Tiles', start: '2026-09-24', end: '2026-10-01', priority: 'Medium', resp: 'Tiling Team', dep: '', status: 'Not Started', pct: 0, remarks: 'Tiles delivered' },
  { id: 14, phase: 'Finishes', name: 'Flooring', start: '2026-10-02', end: '2026-10-10', priority: 'Medium', resp: 'Tiling Team', dep: 'False Ceiling', status: 'Not Started', pct: 0, remarks: 'Tiles delivered' },
  { id: 15, phase: 'Finishes', name: 'Kitchen Counter', start: '2026-10-03', end: '2026-10-09', priority: 'Medium', resp: 'Kitchen Vendor', dep: 'Wall Tiles', status: 'Not Started', pct: 0, remarks: 'Full body tile delivered' },
  { id: 16, phase: 'Finishes', name: 'Bathroom Counter', start: '2026-09-24', end: '2026-09-29', priority: 'Medium', resp: 'Tiling Team', dep: 'Wall Tiles', status: 'Not Started', pct: 0, remarks: 'Full body tile delivered' },
  { id: 17, phase: 'Finishes', name: 'Paint', start: '2026-10-11', end: '2026-10-16', priority: 'Medium', resp: 'Painter', dep: 'Flooring', status: 'Not Started', pct: 0, remarks: 'Shade not selected' },
  { id: 18, phase: 'Openings', name: 'Sliding Doors', start: '2026-10-04', end: '2026-10-10', priority: 'Medium', resp: 'Door/Window Vendor', dep: 'Wall Tiles', status: 'Not Started', pct: 0, remarks: '4 nos — material to be specified' },
  { id: 19, phase: 'Openings', name: 'Windows', start: '2026-10-04', end: '2026-10-10', priority: 'Medium', resp: 'Door/Window Vendor', dep: 'Wall Tiles', status: 'Not Started', pct: 0, remarks: '5 nos — details pending' },
  { id: 20, phase: 'Openings', name: 'MS Fabrication Stairs', start: '2026-09-14', end: '2026-09-18', priority: 'Medium', resp: 'Fabricator (Izhan)', dep: 'Civil/Stairs', status: 'Completed', pct: 100, remarks: 'Red oxide & paint done' },
  { id: 21, phase: 'Interior', name: 'Mirrors', start: '2026-10-11', end: '2026-10-13', priority: 'Low', resp: 'Interior Vendor', dep: 'Paint', status: 'Not Started', pct: 0, remarks: '2 nos — selection pending' },
  { id: 22, phase: 'Interior', name: 'Furniture', start: '2026-10-11', end: '2026-10-25', priority: 'Medium', resp: 'Furniture Vendor', dep: 'Paint', status: 'Not Started', pct: 0, remarks: 'Details pending' },
  { id: 23, phase: 'Interior', name: 'Data / CCTV', start: '2026-10-11', end: '2026-10-18', priority: 'Medium', resp: 'ELV Vendor', dep: 'Electrical', status: 'Not Started', pct: 0, remarks: 'No details yet' },
  { id: 24, phase: 'Interior', name: 'UPS / Inverter', start: '2026-10-18', end: '2026-10-22', priority: 'Low', resp: 'Electrical Vendor', dep: 'Electrical', status: 'Not Started', pct: 0, remarks: 'No details yet' },
];

export const INITIAL_MATERIALS: MaterialItem[] = [
  { id: 1, name: 'Waterproofing', mat: 'Delivered', work: 'Pending', resp: 'Aditya Construction', deadline: '07 Sep 2026', phase: 'Critical Civil & External' },
  { id: 2, name: 'Plaster', mat: 'Delivered', work: 'In Progress', resp: 'RS Construction', deadline: '12 Sep 2026', phase: 'Critical Civil & External' },
  { id: 3, name: 'Stone Masonary', mat: 'To be Delivered', work: 'In Progress', resp: 'RS Construction', deadline: '28 Sep 2026', phase: 'Critical Civil & External' },
  { id: 4, name: 'Brick Masonary', mat: 'Delivered', work: 'In Progress', resp: 'RS Construction', deadline: '13 Sep 2026', phase: 'Critical Civil & External' },
  { id: 5, name: 'Electrical', mat: 'Selection Pending', work: 'Pending', resp: 'Ganesh Ji', deadline: '28 Oct 2026', phase: 'Services' },
  { id: 6, name: 'BT Plumbing', mat: 'Partial', work: 'Not Started', resp: 'Plumbing Team', deadline: '30 Sep 2026', phase: 'Services' },
  { id: 7, name: 'Kitchen Counter', mat: 'Delivered', work: 'Pending', resp: 'Kitchen Vendor', deadline: '20 Sep 2026', phase: 'Finishes' },
  { id: 8, name: 'Bathroom Counter', mat: 'Delivered', work: 'Pending', resp: 'Tiling Team', deadline: '15 Sep 2026', phase: 'Finishes' },
  { id: 9, name: 'MS Fab. Stairs', mat: 'Delivered', work: 'Complete', resp: 'Fabricator (Izhan)', deadline: '18 Sep 2026', phase: 'Openings' },
  { id: 10, name: 'MS Fab. Roof', mat: 'To be Delivered', work: 'Pending', resp: 'Fabricator', deadline: '18 Sep 2026', phase: 'Critical Civil & External' },
  { id: 11, name: 'Roof Flooring', mat: 'Selection Pending', work: 'Pending', resp: 'Nanak', deadline: '22 Sep 2026', phase: 'Critical Civil & External' },
  { id: 12, name: 'False Ceiling', mat: 'Delivered', work: 'In Progress', resp: 'Vendor', deadline: '08 Oct 2026', phase: 'Finishes' },
  { id: 13, name: 'Flooring Tiles', mat: 'Delivered', work: 'Pending', resp: 'Tiling Team', deadline: '10 Oct 2026', phase: 'Finishes' },
  { id: 14, name: 'Wall Tiles', mat: 'Delivered', work: 'Pending', resp: 'Tiling Team', deadline: '01 Oct 2026', phase: 'Finishes' },
  { id: 15, name: 'Paint', mat: 'Selection Pending', work: 'Pending', resp: 'Painter', deadline: '16 Oct 2026', phase: 'Finishes' },
  { id: 16, name: 'Furniture', mat: 'To be Delivered', work: 'Pending', resp: 'Vendor', deadline: '25 Oct 2026', phase: 'Interior' },
  { id: 17, name: 'Sliding Doors', mat: 'Selection Pending', work: 'Pending', resp: 'Hyper Interiors', deadline: '10 Oct 2026', phase: 'Openings' },
  { id: 18, name: 'Windows', mat: 'Selection Pending', work: 'Pending', resp: 'Hyper Interiors', deadline: '10 Oct 2026', phase: 'Openings' },
  { id: 19, name: 'Swimming Pool', mat: 'To be Delivered', work: 'In Progress', resp: 'DD Pools', deadline: '26 Sep 2026', phase: 'Swimming Pool' },
  { id: 20, name: 'Outer Area Dev.', mat: 'Delivered', work: 'In Progress', resp: 'RS Construction', deadline: '26 Sep 2026', phase: 'Critical Civil & External' },
];
